### ISSUE TITLE
Add current getting started instructions

### ISSUE THREAD

**Issue by jmeisel** [CommerceDataService/citysdk#14]
Currently, the developer site only references the older CitySDK version and JS library.  

A new "Getting Started (Node JS)" link should be created under Guides with this information:

https://github.com/tshrestha/citysdk/blob/master/src/api/README.md

**Comment by neka-io** [comment]
From what Tejen said, that README is also outdated. For example I know that the endpoints are wrong. I don't know what else about is needs to be updated.

**Comment by jmeisel** [comment]
I was just chatting with Logan, he thinks this is the latest README
https://github.com/uscensusbureau/citysdk/blob/master/src/api/README.md
